# Generated by Django 3.2.4 on 2021-07-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210707_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.TextField(default='Demo'),
        ),
    ]
