# Generated by Django 3.2.4 on 2021-07-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.TextField(default='Unknown'),
        ),
    ]
